name: Deploy Portfolio
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_S3_BUCKET_URL: ${{ secrets.NEXT_PUBLIC_S3_BUCKET_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Deploy HTML files to S3
        run: |
          aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.html" \
            --metadata-directive REPLACE \
            --cache-control max-age=0,no-cache,no-store,must-revalidate \
            --content-type "text/html; charset=utf-8"

      - name: Deploy CSS files to S3
        run: |
          aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.css" \
            --metadata-directive REPLACE \
            --cache-control max-age=31536000,public \
            --content-type "text/css"

      - name: Deploy JavaScript files to S3
        run: |
          aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.js" \
            --metadata-directive REPLACE \
            --cache-control max-age=31536000,public \
            --content-type "application/javascript"

      - name: Deploy remaining static assets
        run: |
          aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*.html" \
            --exclude "*.css" \
            --exclude "*.js" \
            --metadata-directive REPLACE \
            --cache-control max-age=31536000,public

# name: Deploy Portfolio
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18"

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: List build output
#         run: ls -la out/

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: af-south-1

#       - name: Deploy to S3
#         run: aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET }} --delete --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html

#       - name: Verify S3 upload
#         run: aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }}
